### ISSUE TITLE
Volume on Android

### ISSUE THREAD

**Issue by grosssmutttr** [myflashlab/speech-ANE#2]
Hi there,

If you use the tts method the text is spoken on the maximum level even if you set the volume down before. It automatically sets the volume to max.

Would be nice to have a fix :dancer: 
I don't know whether this issue also happens on iOS.

**Comment by grosssmutttr** [comment]
I never use _ex.volume so it should use the media volume like in previous speech ane versions?

**Comment by myflashlab** [comment]
we are working on V6.0 and we are addressing the Volume problem too.

**Comment by grosssmutttr** [comment]
Thanks a lot! Can you give me the approx. date when I can get the new version?

**Comment by myflashlab** [comment]
you should expect it by mid-August I think. we have some other ANEs to publish before then.

**Comment by grosssmutttr** [comment]
Ok thanks.

**Comment by grosssmutttr** [comment]
These are the error reports with Speech Ane version 6.0:
1. Galaxy S3 (m0) Android 4.3
   java.lang.RuntimeException: Error receiving broadcast Intent { act=android.speech.action.GET_LANGUAGE_DETAILS flg=0x10 } in com.doitflash.speech.speechToText.LanguageDetailsChecker@428acf10
   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
   at android.os.Handler.handleCallback(Handler.java:730)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:176)
   at android.app.ActivityThread.main(ActivityThread.java:5419)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:525)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
   at dalvik.system.NativeStart.main(Native Method)
   Caused by: java.lang.IllegalArgumentException
   at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
   at com.doitflash.speech.speechToText.LanguageDetailsChecker.toDispatchResults(LanguageDetailsChecker.java:53)
   at com.doitflash.speech.speechToText.LanguageDetailsChecker.onReceive(LanguageDetailsChecker.java:45)
   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
2. Galaxy S3 Mini (golden) Android 4.1
   java.lang.IllegalArgumentException
   at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
   at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:105)
   at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:640)
   at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
   at android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:1296)
   at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
   at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4867)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
   at dalvik.system.NativeStart.main(Native Method)
3. ONE TOUCH 4033X Android 4.2
   java.lang.RuntimeException: Error receiving broadcast Intent { act=android.speech.action.GET_LANGUAGE_DETAILS flg=0x10 } in com.doitflash.speech.speechToText.LanguageDetailsChecker@4101e7c0
   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
   at android.os.Handler.handleCallback(Handler.java:800)
   at android.os.Handler.dispatchMessage(Handler.java:100)
   at android.os.Looper.loop(Looper.java:194)
   at android.app.ActivityThread.main(ActivityThread.java:5400)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:525)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
   at dalvik.system.NativeStart.main(Native Method)
   Caused by: java.lang.IllegalArgumentException
   at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
   at com.doitflash.speech.speechToText.LanguageDetailsChecker.toDispatchResults(LanguageDetailsChecker.java:53)
   at com.doitflash.speech.speechToText.LanguageDetailsChecker.onReceive(LanguageDetailsChecker.java:45)
   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:788)
4. Galaxy S5 Mini (kminilte) Android 4.4
   java.lang.RuntimeException: Error receiving broadcast Intent { act=android.speech.action.GET_LANGUAGE_DETAILS flg=0x10 } in com.doitflash.speech.speechToText.LanguageDetailsChecker@43330cc0
   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:782)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:146)
   at android.app.ActivityThread.main(ActivityThread.java:5694)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
   at dalvik.system.NativeStart.main(Native Method)
   Caused by: java.lang.IllegalArgumentException
   at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
   at com.doitflash.speech.speechToText.LanguageDetailsChecker.toDispatchResults(LanguageDetailsChecker.java:53)
   at com.doitflash.speech.speechToText.LanguageDetailsChecker.onReceive(LanguageDetailsChecker.java:45)
   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:772)

I think you're missing some exception checks via try/catch block?
