### ISSUE TITLE
Many error reports

### ISSUE THREAD

**Issue by grosssmutttr** [myflashlab/speech-ANE#3]
Android 4.4, Galaxy Tab3 10.1:
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.speech.action.GET_LANGUAGE_DETAILS flg=0x10 } in com.doitflash.speech.speechToText.LanguageDetailsChecker@21d36af8
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:782)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.speechToText.LanguageDetailsChecker.toDispatchResults(LanguageDetailsChecker.java:53)
at com.doitflash.speech.speechToText.LanguageDetailsChecker.onReceive(LanguageDetailsChecker.java:45)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:772)

Android 4.2, SurfTab ST70204-3:
java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:105)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:640)
at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
at android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:1297)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1101)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1118)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)

Android 4.2, Galaxy S3 Mini Value
java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:111)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:643)
at android.speech.tts.TextToSpeech.access$1100(TextToSpeech.java:52)
at android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:1313)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1106)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1123)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5365)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)

Android 5.0, Samsung S5
java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:105)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
at android.speech.tts.TextToSpeech.access$1400(TextToSpeech.java:59)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2147)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2102)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5832)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Android 5.0, Samsung S4
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.speech.action.GET_LANGUAGE_DETAILS flg=0x10 } in com.doitflash.speech.speechToText.LanguageDetailsChecker@20c3677b
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:933)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5942)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.speechToText.LanguageDetailsChecker.toDispatchResults(LanguageDetailsChecker.java:53)
at com.doitflash.speech.speechToText.LanguageDetailsChecker.onReceive(LanguageDetailsChecker.java:45)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:923)

and so on....

**Comment by grosssmutttr** [comment]
Android 4.2, HTC Desire 310 
java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:105)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:640)
at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
at android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:1297)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1131)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1148)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5391)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

Android 4.4, XPeria M2
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.speech.action.GET_LANGUAGE_DETAILS flg=0x10 } in com.doitflash.speech.speechToText.LanguageDetailsChecker@419d04c8
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:820)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5212)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException
at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
at com.doitflash.speech.speechToText.LanguageDetailsChecker.toDispatchResults(LanguageDetailsChecker.java:53)
at com.doitflash.speech.speechToText.LanguageDetailsChecker.onReceive(LanguageDetailsChecker.java:45)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:810)

**Comment by myflashlab** [comment]
Thanks for posting the error logs. we'll look into this.

**Comment by grosssmutttr** [comment]
I think it is possible that these users haven't set the Google Speech Api in their settings...

**Comment by myflashlab** [comment]
Let me know if you still have these problems with the new version?

**Comment by grosssmutttr** [comment]
java.lang.IllegalArgumentException
    at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
    at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:105)
    at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:627)
    at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
    at android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:1279)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1068)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1085)
    at android.os.Handler.handleCallback(Handler.java:605)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4424)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
    at dalvik.system.NativeStart.main(Native Method)

java.lang.IllegalArgumentException
    at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
    at com.doitflash.speech.textToSpeech.TTS$1.onInit(TTS.java:105)
    at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:640)
    at android.speech.tts.TextToSpeech.access$1000(TextToSpeech.java:52)
    at android.speech.tts.TextToSpeech$Connection.onServiceConnected(TextToSpeech.java:1296)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4867)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
    at dalvik.system.NativeStart.main(Native Method)

Xperia Tipo (ST21i)
Xperia Miro (ST23i)
Galaxy S3 Mini (golden)

These are still reported by users...
